name: YouTube Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes

concurrency:
  group: youtube-tracker-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Deno
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Setup FFmpeg
        run: |
          if ! command -v ffmpeg &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y ffmpeg
          else
            echo "ffmpeg is already installed on the runner"
          fi

      - name: Install Python Dependencies
        run: |
          pip install -U https://github.com/yt-dlp/yt-dlp/archive/master.zip
          pip install requests pytz google-api-python-client google-auth-httplib2 google-auth-oauthlib curl-cffi

      - name: Setup Cloudflare WARP
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ focal main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update && sudo apt-get install -y cloudflare-warp
          warp-cli --accept-tos registration new
          warp-cli --accept-tos connect
          sleep 5
          curl -sS https://cloudflare.com/cdn-cgi/trace | grep warp

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID_2 }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET_2 }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN_2 }}
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
        run: |
          if [ -n "$YOUTUBE_COOKIES" ]; then
            echo "$YOUTUBE_COOKIES" | base64 --decode > cookies.txt || echo "$YOUTUBE_COOKIES" > cookies.txt
          fi
          python main.py